### ISSUE TITLE
docs: include notes for Win32

### ISSUE THREAD

**Issue by GitMensch** [danielbayley/vscode-custom-app-icons#2]
> named it icon.ico

@Ant767 It should be named `code.ico`… Windows users need to match these files https://github.com/microsoft/vscode/tree/main/resources/win32. This is linked to in the README, but maybe it could be more clear?

_Originally posted by @danielbayley in https://github.com/danielbayley/vscode-custom-app-icons/issues/1#issuecomment-1722453573_

--------------------------

Actually the README has only a _link_ to _darwin_ icons. I suggest to make a sub-header for each platform with a note what to place where, which may be different for vscode/vscodium/others, too.

**Comment by danielbayley** [comment]
> I suggest to make a sub-header for each platform with a note what to place where, which may be different for vscode/vscodium/others, too.

@GitMensch I added a

> [!TIP]
> in the README

See here: https://github.com/danielbayley/vscode-custom-app-icons#usage
